export { arch_elf }

import { rallyPoint } from "./general_rallypoint"
import { eatTree,root } from "./general_elf"
import { interact } from "./general_interact"


let arch_elf = {
    生命之树:{
        ico:[1,5],
        btn:[
            {
                tag:'小精灵',
                tip:'以前是男人，后来变成了女人',
                ico:[1,2],
                pos:[1,1],
                key:['[ewsp]'],
                val:'W',
                map:['Hotkey']
            },
            {
                tag:'自然的祝福',
                tip:'以前是男人，后来变成女人了',
                ico:[11,6],
                pos:[3,1],
                key:['[Renb]'],
                val:'N',
                map:['Hotkey']
            },
            {
                tag:'背包升级',
                tip:'',
                ico:[12,6],
                pos:[4,1],
                key:['[Repm]'],
                val:'N',
                map:['Hotkey']
            },
            {
                tag:'升级',
                tip:'生命之树升级为远古之树，远古之树升级为永恒之树',
                ico:[12,7],
                pos:[1,3],
                key:['[etoa]','[etoe]'],
                val:'U',
                map:['Hotkey']
            },
            {
                tag:'缠绕金矿',
                tip:'',
                ico:[4,6],
                pos:[2,3],
                key:['[Aent]'],
                val:'G',
                map:['Hotkey']
            },
            rallyPoint,eatTree,root
        ]
    },
    战争古树:{
        ico:[2,5],
        btn:[
            {
                tag:'弓箭手',
                tip:'',
                ico:[2,2],
                pos:[1,1],
                key:['[earc]'],
                val:'A',
                map:['Hotkey']
            },
            {
                tag:'女猎手',
                tip:'',
                ico:[3,2],
                pos:[2,1],
                key:['[esen]'],
                val:'H',
                map:['Hotkey']
            },
            {
                tag:'投刃车',
                tip:'',
                ico:[4,2],
                pos:[3,1],
                key:['[ebal]'],
                val:'T',
                map:['Hotkey']
            },
            {
                tag:'精准射击',
                tip:'',
                ico:[7,1],
                pos:[1,2],
                key:['[Remk]'],
                val:'M',
                map:['Hotkey']
            },
            {
                tag:'硬弓',
                tip:'',
                ico:[5,4],
                pos:[1,3],
                key:['[Reib]'],
                val:'I',
                map:['Hotkey']
            },
            {
                tag:'月刃',
                tip:'',
                ico:[8,1],
                pos:[2,2],
                key:['[Remg]'],
                val:'G',
                map:['Hotkey']
            },
            {
                tag:'猫头鹰哨兵',
                tip:'',
                ico:[6,4],
                pos:[2,3],
                key:['[Resc]'],
                val:'S',
                map:['Hotkey']
            },
            {
                tag:'穿刺之刃',
                tip:'',
                ico:[7,4],
                pos:[3,2],
                key:['[Repb]'],
                val:'S',
                map:['Hotkey']
            },
            rallyPoint,eatTree,root
        ]
    },
    猎手大厅:{
        ico:[3,5],
        btn:[
            {
                tag:'月神之力',
                tip:'',
                ico:[5,5],
                pos:[1,1],
                key:['[Resm]'],
                val:'M',
                map:3
            },
            {
                tag:'野性之力',
                tip:'',
                ico:[6,5],
                pos:[2,1],
                key:['[Resw]'],
                val:'W',
                map:3
            },
            {
                tag:'月神之甲',
                tip:'',
                ico:[5,6],
                pos:[1,2],
                key:['[Rema]'],
                val:'A',
                map:3
            },
            {
                tag:'野性之甲',
                tip:'',
                ico:[6,6],
                pos:[2,2],
                key:['[Rerh]'],
                val:'R',
                map:3
            },
            {
                tag:'夜视',
                tip:'',
                ico:[7,5],
                pos:[3,1],
                key:['[Reuv]'],
                val:'U',
                map:['Hotkey']
            },
            {
                tag:'月井之春',
                tip:'',
                ico:[8,5],
                pos:[4,1],
                key:['[Rews]'],
                val:'E',
                map:['Hotkey']
            },
        ]
    },
    远古守护者:{
        ico:[4,5],
        btn:[
            eatTree,root
        ]
    },
    月亮井:{
        ico:[1,6],
        btn:[
            {
                tag:'使用井水',
                tip:'',
                ico:[10,6],
                pos:[1,1],
                key:['[Ambt]'],
                val:'R',
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    长者祭坛:{
        ico:[2,6],
        btn:[
            {
                tag:'守望者',
                tip:'',
                ico:[4,1],
                pos:[1,2],
                key:['[Ewar]'],
                val:'W',
                map:['Hotkey']
            },
            {
                tag:'恶魔猎手',
                tip:'',
                ico:[1,1],
                pos:[1,3],
                key:['[Edem]'],
                val:'D',
                map:['Hotkey']
            },
            {
                tag:'恶魔猎手',
                tip:'',
                ico:[2,1],
                pos:[2,3],
                key:['[Ekee]'],
                val:'K',
                map:['Hotkey']
            },
            {
                tag:'月女祭祀',
                tip:'',
                ico:[3,1],
                pos:[3,3],
                key:['[Emoo]'],
                val:'P',
                map:['Hotkey']
            },
        ]
    },
    知识古树:{
        ico:[3,6],
        btn:[
            {
                tag:'树妖',
                tip:'',
                ico:[1,3],
                pos:[1,1],
                key:['[edry]'],
                val:'D',
                map:['Hotkey']
            },
            {
                tag:'利爪德鲁伊',
                tip:'',
                ico:[2,3],
                pos:[2,1],
                key:['[edoc]'],
                val:'C',
                map:['Hotkey']
            },
            {
                tag:'山岭巨人',
                tip:'',
                ico:[3,3],
                pos:[3,1],
                key:['[emtg]'],
                val:'G',
                map:['Hotkey']
            },
            {
                tag:'研究驱散',
                tip:'',
                ico:[5,3],
                pos:[1,3],
                key:['[Resi]'],
                val:'S',
                map:['Hotkey']
            },
            {
                tag:'利爪德鲁伊升级',
                tip:'',
                ico:[6,3],
                pos:[2,3],
                key:['[Redc]'],
                val:'S',
                map:2
            },
            {
                tag:'研究利爪之印',
                tip:'让利爪德鲁伊在熊形态下，使用咆哮技能',
                ico:[6,2],
                pos:[2,2],
                key:['[Reeb]'],
                val:'M',
                map:['Hotkey']
            },
            {
                tag:'研究硬化皮肤',
                tip:'',
                ico:[7,2],
                pos:[3,2],
                key:['[Rehs]'],
                val:'H',
                map:['Hotkey']
            },
            {
                tag:'研究抗性皮肤',
                tip:'',
                ico:[7,3],
                pos:[3,3],
                key:['[Rers]'],
                val:'T',
                map:['Hotkey']
            },
            rallyPoint,root
        ]
    },
    被缠绕的金矿:{
        ico:[4,6],
        btn:[
            {
                tag:'装载小精灵',
                tip:'',
                ico:[5,7],
                pos:[1,3],
                key:['[Slo2]'],
                val:'L',
                map:['Hotkey']
            },
            {
                tag:'卸载小精灵',
                tip:'',
                ico:[6,7],
                pos:[2,3],
                key:['[Adri]'],
                val:'U',
                map:['Hotkey']
            },
        ]
    },
    风之古树:{
        ico:[1,7],
        btn:[
            {
                tag:'角鹰兽',
                tip:'',
                ico:[1,4],
                pos:[1,1],
                key:['[ehip]'],
                val:'H',
                map:['Hotkey']
            },
            {
                tag:'猛禽德鲁伊',
                tip:'',
                ico:[2,4],
                pos:[2,1],
                key:['[edot]'],
                val:'T',
                map:['Hotkey']
            },
            {
                tag:'精灵龙',
                tip:'',
                ico:[3,4],
                pos:[3,1],
                key:['[efdr]'],
                val:'F',
                map:['Hotkey']
            },
            {
                tag:'驯服角鹰兽',
                tip:'1.32已取消此研究升级，角鹰可直接搭乘弓箭手;改设置只对老版本生效',
                ico:[1,9],
                pos:[1,3],
                key:['[Reht]'],
                val:'I',
                map:['Hotkey']
            },
            {
                tag:'猛禽德鲁伊升级',
                tip:'',
                ico:[8,3],
                pos:[2,3],
                key:['[Redt]'],
                val:'A',
                map:2
            },
            {
                tag:'猛禽之印',
                tip:'让德鲁伊在乌鸦形态下也能释放精灵之火',
                ico:[8,2],
                pos:[2,2],
                key:['[Reec]'],
                val:'M',
                map:['Hotkey']
            },
            rallyPoint,eatTree,root
        ]
    },
    奇美拉栖木:{
        ico:[2,7],
        btn:[
            {
                tag:'研究腐蚀吐息',
                tip:'',
                ico:[8,4],
                pos:[1,3],
                key:['[Recb]'],
                val:'B',
                map:['Hotkey']
            },
        ]
    },
    奇迹古树:{
        ico:[3,7],
        btn:[
            eatTree,root,interact
        ]
    },
    精灵建造:{
        ico:[4,7],
        btn:[
            {
                tag:'生命之树',
                tip:'',
                ico:[1,5],
                pos:[1,1],
                key:['[etol]'],
                val:'T',
                map:['Hotkey']
            },
            {
                tag:'战争古树',
                tip:'',
                ico:[2,5],
                pos:[2,1],
                key:['[eaom]'],
                val:'R',
                map:['Hotkey']
            },
            {
                tag:'猎手大厅',
                tip:'',
                ico:[3,5],
                pos:[3,1],
                key:['[edob]'],
                val:'H',
                map:['Hotkey']
            },
            {
                tag:'远古守护者',
                tip:'',
                ico:[4,5],
                pos:[4,1],
                key:['[etrp]'],
                val:'P',
                map:['Hotkey']
            },
            {
                tag:'月亮井',
                tip:'',
                ico:[1,6],
                pos:[1,2],
                key:['[emow]'],
                val:'M',
                map:['Hotkey']
            },
            {
                tag:'长者祭坛',
                tip:'',
                ico:[2,6],
                pos:[2,2],
                key:['[eate]'],
                val:'A',
                map:['Hotkey']
            },
            {
                tag:'知识古树',
                tip:'',
                ico:[3,6],
                pos:[3,2],
                key:['[eaoe]'],
                val:'L',
                map:['Hotkey']
            },
            {
                tag:'风之古树',
                tip:'',
                ico:[1,7],
                pos:[1,3],
                key:['[eaow]'],
                val:'W',
                map:['Hotkey']
            },
            {
                tag:'奇美拉栖木',
                tip:'',
                ico:[2,7],
                pos:[2,3],
                key:['[edos]'],
                val:'C',
                map:['Hotkey']
            },
            {
                tag:'奇迹古树',
                tip:'',
                ico:[3,7],
                pos:[3,3],
                key:['[eden]'],
                val:'D',
                map:['Hotkey']
            },
        ]
    }
}

arch_elf.奇迹古树.btn[2].pos = [4,2]