export { unit_human }

import { hitground } from './general_hitground'
import { selectSkill } from "./general_selectSkill"
import { orders } from "./general_orders"
import { repair } from "./general_repair"
import { harvest } from "./general_harvest"

let unit_human = {
    大法师:{
        key:'[Hamg]',
        val:'A',
        ico:[1,1],
        btn:[
            {
                tag:'暴风雪',
                ico:[9,1],
                pos:[1,3],
                key:'[AHbz]',
                val:'B',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'召唤水元素',
                ico:[10,1],
                pos:[2,3],
                key:'[AHwe]',
                val:'W',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'辉煌光环',
                ico:[11,1],
                pos:[3,3],
                key:'[AHab]',
                val:'R',
                map:['Researchhotkey']
            },
            {
                tag:'群体传送',
                ico:[12,1],
                pos:[4,3],
                key:'[AHmt]',
                val:'T',
                map:['Hotkey','Researchhotkey']
            },
            selectSkill,
        ]
    },
    山丘之王:{
        ico:[2,1],
        btn:[
            selectSkill,
            {
                tag:'风暴之锤',
                ico:[9,2],
                pos:[1,3],
                key:'[AHtb]',
                val:'Q',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'雷霆一击',
                ico:[10,2],
                pos:[2,3],
                key:'[AHtc]',
                val:'E',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'重击',
                ico:[11,2],
                pos:[3,3],
                key:'[AHbh]',
                val:'R',
                map:['Researchhotkey']
            },
            {
                tag:'天神下凡',
                ico:[12,2],
                pos:[4,3],
                key:'[AHav]',
                val:'V',
                map:['Hotkey','Unhotkey','Researchhotkey']
            },
        ]
    },
    圣骑士:{

        ico:[3,1],
        btn:[
            selectSkill,
            {
                tag:'圣光',
                ico:[9,3],
                pos:[1,3],
                key:'[AHhb]',
                val:'Q',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'无敌',
                ico:[10,3],
                pos:[2,3],
                key:'[AHds]',
                val:'E',
                map:['Hotkey','Unhotkey','Researchhotkey']
            },
            {
                tag:'专注光环',
                ico:[11,3],
                pos:[3,3],
                key:'[AHad]',
                val:'R',
                map:['Researchhotkey']
            },
            {
                tag:'复活',
                ico:[12,3],
                pos:[4,3],
                key:'[AHre]',
                val:'V',
                map:['Hotkey','Researchhotkey']
            },
        ]
    },
    血魔法师:{
        ico:[4,1],
        btn:[
            selectSkill,
            {
                tag:'烈焰风暴',
                ico:[9,4],
                pos:[1,3],
                key:'[AHfs]',
                val:'F',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'放逐',
                ico:[10,4],
                pos:[2,3],
                key:'[AHbn]',
                val:'B',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'法力虹吸',
                ico:[11,4],
                pos:[3,3],
                key:'[AHdr]',
                val:'N',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'召唤凤凰',
                ico:[12,4],
                pos:[4,3],
                key:'[AHpx]',
                val:'X',
                map:['Hotkey','Researchhotkey']
            },
        ]
    },
    农民:{
        ico:[1,2],
        btn:[
            repair,
            harvest,
            {
                tag:'民兵',
                ico:[6,1],
                pos:[2,3],
                key:'[Amil]',
                val:'C',
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'人类建造',
                ico:[4,7],
                pos:[1,3],
                key:'[CmdBuildHuman]',
                val:'B',
                map:['Hotkey']
            },
        ]
    },
    步兵:{
        ico:[2,2],
        btn:[
            {
                tag:'防御',
                ico:[7,1],
                pos:[1,3],
                key:'[Adef]1',
                val:'D',
                map:['Hotkey']
            },
            {
                tag:'取消防御',
                ico:[8,1],
                pos:[2,3],
                key:'[Adef]2',
                val:'D',
                map:['Unhotkey']
            },
        ]
    },
    火枪手:{
        ico:[3,2],
    },
    骑士:{
        key:'[hkni]',
        val:'A',
        ico:[4,2],
    },
    女巫:{
        key:'[hsor]',
        val:'S',
        ico:[1,3],
        btn:[
            {
                tag:'减速',
                ico:[5,2],
                pos:[1,3],
                key:'[Aslo]',
                val:'Q',
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'隐身术',
                ico:[6,2],
                pos:[2,3],
                key:'[Aivs]',
                val:'Z',
                map:['Hotkey']
            },
            {
                tag:'变形术',
                ico:[7,2],
                pos:[3,3],
                key:'[Aply]',
                val:'X',
                map:['Hotkey']
            },
        ]
    },
    牧师:{
        key:'[hmpr]',
        val:'R',
        ico:[2,3],
        btn:[
            {
                tag:'治疗',
                ico:[5,3],
                pos:[1,3],
                key:'[Ahea]',
                val:'E',
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'驱散',
                ico:[6,3],
                pos:[2,3],
                key:'[Adis]',
                val:'D',
                map:['Hotkey']
            },
            {
                tag:'心灵之火',
                ico:[7,3],
                pos:[3,3],
                key:'[Ainf]',
                val:'F',
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    破法者:{
        key:'[hspt]',
        val:'B',
        ico:[3,3],
        btn:[
            {
                tag:'魔法盗取',
                ico:[8,6],
                pos:[1,3],
                key:'[Asps]',
                val:'T',
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'魔法控制',
                ico:[8,7],
                pos:[2,3],
                key:'[Acmg]',
                val:'C',
                map:['Hotkey']
            },
        ]
    },
    龙鹰:{
        key:'[hdhw]',
        val:'D',
        ico:[4,3],
        btn:[
            {
                tag:'空中枷锁',
                ico:[8,2],
                pos:[1,3],
                key:'[Amls]',
                val:'E',
                map:['Hotkey']
            },
            {
                tag:'蔽目乌云',
                ico:[8,3],
                pos:[2,3],
                key:'[Aclf]',
                val:'C',
                map:['Hotkey']
            },
        ]
    },
    直升机:{
        key:'[hgyr]',
        val:'F',
        ico:[1,4],
    },
    迫击炮:{
        key:'[hmtm]',
        val:'A',
        ico:[2,4],
        btn:[
            {
                tag:'照明弹',
                ico:[8,4],
                pos:[1,3],
                key:'[Afla]',
                val:'F',
                map:['Hotkey']
            },
            hitground
        ]
    },
    蒸汽机车:{
        key:['[hmtt]','[hrtt]'],
        val:'E',
        ico:[3,4],
    },
    狮鹫骑士:{
        key:'[hgry]',
        val:'G',
        ico:[4,4],
    },
}

Object.keys(unit_human).forEach(function(key){
    if(!unit_human[key].btn){
        unit_human[key].btn = []
    }
    unit_human[key].btn.push(...orders)

})