import {unit_elf} from "./unit_elf"

export { unit_orc }

import { hitground } from './general_hitground'
import { selectSkill } from "./general_selectSkill"
import { orders } from "./general_orders"
import { repair } from "./general_repair"
import { harvest } from "./general_harvest"

let unit_orc = {
    剑圣:{
        ico:[1,1],
        btn:[
            {
                tag:'疾风步',
                tip:'',
                ico:[9,3],
                pos:[1,3],
                key:'[AOwk]',
                val:'W',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'镜像',
                tip:'',
                ico:[10,3],
                pos:[2,3],
                key:'[AOmi]',
                val:'R',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'致命一击',
                tip:'',
                ico:[11,3],
                pos:[3,3],
                key:'[AOcr]',
                val:'C',
                map:['Researchhotkey']
            },
            {
                tag:'剑刃风暴',
                tip:'',
                ico:[12,3],
                pos:[4,3],
                key:'[AOww]',
                val:'B',
                map:['Hotkey','Researchhotkey']
            },
            selectSkill
        ]
    },
    先知:{
        ico:[2,1],
        btn:[
            {
                tag:'闪电链',
                tip:'',
                ico:[9,4],
                pos:[1,3],
                key:'[AOcl]',
                val:'C',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'透视',
                tip:'',
                ico:[10,4],
                pos:[2,3],
                key:'[AOfs]',
                val:'F',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'幽灵狼',
                tip:'',
                ico:[11,4],
                pos:[3,3],
                key:'[AOsf]',
                val:'T',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'地震术',
                tip:'',
                ico:[12,4],
                pos:[4,3],
                key:'[AOeq]',
                val:'E',
                map:['Hotkey','Researchhotkey']
            },
            selectSkill
        ]
    },
    牛头人酋长:{
        ico:[3,1],
        btn:[
            {
                tag:'震荡波',
                tip:'',
                ico:[9,6],
                pos:[1,3],
                key:'[AOsh]',
                val:'W',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'战争践踏',
                tip:'',
                ico:[10,6],
                pos:[2,3],
                key:'[AOws]',
                val:'T',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'坚韧光环',
                tip:'',
                ico:[11,6],
                pos:[3,3],
                key:'[AOae]',
                val:'E',
                map:['Researchhotkey']
            },
            {
                tag:'重生',
                tip:'',
                ico:[12,6],
                pos:[4,3],
                key:'[AOre]',
                val:'R',
                map:['Researchhotkey']
            },
            selectSkill
        ]
    },
    巨魔巫医:{
        ico:[4,1],
        btn:[
            {
                tag:'治疗波',
                tip:'',
                ico:[9,5],
                pos:[1,3],
                key:'[AOhw]',
                val:'E',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'毒蛇守卫',
                tip:'',
                ico:[10,5],
                pos:[2,3],
                key:'[AOsw]',
                val:'W',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'妖术',
                tip:'',
                ico:[11,5],
                pos:[3,3],
                key:'[AOhx]',
                val:'X',
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'无毒',
                tip:'喘气能回血，嘘嘘能回蓝，跳舞能无敌',
                ico:[12,5],
                pos:[4,3],
                key:'[AOvd]',
                val:'V',
                map:['Hotkey','Researchhotkey']
            },
            selectSkill
        ]
    },
    苦工:{
        ico:[1,2],
        btn:[
            {
                tag:'建造',
                tip:'',
                ico:[4,7],
                pos:[1,3],
                key:'[CmdBuildOrc]',
                val:'B',
                map:['Hotkey']
            },
            repair,harvest
        ]
    },
    兽人步兵:{
        ico:[2,2],
    },
    猎头者:{
        ico:[3,2],
        btn:[
            {
                tag:'狂暴',
                tip:'',
                ico:[5,7],
                pos:[1,3],
                key:'[Absk]',
                val:'B',
                map:['Hotkey']
            },
        ]
    },
    投石车:{
        ico:[4,2],
        btn:[
            hitground
        ]
    },
    狼骑兵:{
        ico:[1,3],
        btn:[
            {
                tag:'诱捕',
                tip:'',
                ico:[5,4],
                pos:[1,3],
                key:'[Aens]',
                val:'E',
                map:['Hotkey']
            },
        ]
    },
    双足飞龙:{
        ico:[2,3],

    },
    科多兽:{
        ico:[3,3],
        btn:[
            {
                tag:'吞噬',
                tip:'',
                ico:[7,7],
                pos:[1,3],
                key:'[Adev]',
                val:'D',
                map:['Hotkey']
            },
        ]
    },
    自爆蝙蝠:{
        ico:[4,3],
        btn:[
            {
                tag:'不稳定化合物',
                tip:'',
                ico:[6,7],
                pos:[1,3],
                key:'[Auco]',
                val:'C',
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    萨满:{
        ico:[1,4],
        btn:[
            {
                tag:'净化',
                tip:'',
                ico:[9,2],
                pos:[1,3],
                key:'[Aprg]',
                val:'G',
                map:['Hotkey']
            },
            {
                tag:'闪电盾',
                tip:'',
                ico:[10,2],
                pos:[2,3],
                key:'[Alsh]',
                val:'L',
                map:['Hotkey']
            },
            {
                tag:'嗜血',
                tip:'',
                ico:[11,2],
                pos:[3,3],
                key:'[Ablo]',
                val:'B',
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    巫医:{
        ico:[2,4],
        btn:[
            {
                tag:'侦查岗哨',
                tip:'',
                ico:[9,1],
                pos:[1,3],
                key:'[Aeye]',
                val:'W',
                map:['Hotkey']
            },
            {
                tag:'静止陷阱',
                tip:'',
                ico:[10,1],
                pos:[2,3],
                key:'[Asta]',
                val:'T',
                map:['Hotkey']
            },
            {
                tag:'治疗守卫',
                tip:'',
                ico:[11,1],
                pos:[3,3],
                key:'[Ahwd]',
                val:'E',
                map:['Hotkey']
            },
        ]
    },
    灵魂行者:{
        ico:[3,4],
        btn:[
            {
                tag:'灵魂链接',
                tip:'',
                ico:[5,6],
                pos:[1,3],
                key:'[Aspl]',
                val:'R',
                map:['Hotkey']
            },
            {
                tag:'消魔',
                tip:'驱散区域内的魔法效果，对敌对召唤单位造成250点伤害',
                ico:[6,6],
                pos:[2,3],
                key:'[Adcn]',
                val:'D',
                map:['Hotkey']
            },
            {
                tag:'先祖之魂',
                tip:'',
                ico:[7,6],
                pos:[3,3],
                key:'[Aast]',
                val:'C',
                map:['Hotkey']
            },
            {
                tag:'肉体/灵魂形态切换',
                tip:'',
                ico:[8,6],
                pos:[4,3],
                key:['[Acpf]','[Aetf]'],
                val:'F',
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    牛头人:{
        ico:[4,4],
    },
}

Object.keys(unit_orc).forEach(function(key){
    if(!unit_orc[key].btn){
        unit_orc[key].btn = []
    }
    unit_orc[key].btn.push(...orders)
})