const storage = require('main/const/storage')
let keys = require(storage + '/keys')

let { 移动,停止,保持,攻击,巡逻,选择技能 } = require("../general_unit")

let unit = {
    娜迦:{
        ico:[1,1],
        btn:[
            {
                tag:'叉状闪电',
                tip:'',
                ico:[5,1],
                pos:[1,3],
                key:['ANfl'],
                val:keys['ANfl'],
            },
            {
                tag:'法力护盾',
                tip:'',
                ico:[6,1],
                pos:[2,3],
                key:['ANms'],
                val:keys['ANms'],
            },
            {
                tag:'冰霜箭矢',
                tip:'',
                ico:[7,1],
                pos:[3,3],
                key:['ANfa'],
                val:keys['ANfa'],
            },
            {
                tag:'飓风',
                tip:'',
                ico:[8,1],
                pos:[4,3],
                key:['ANto'],
                val:keys['ANto'],
            },
            选择技能
        ]
    },
    黑暗游侠:{
        ico:[2,1],
        btn:[
            {
                tag:'黑暗之剑',
                tip:'',
                ico:[5,2],
                pos:[1,3],
                key:['ANba'],
                val:keys['ANba'],
            },
            {
                tag:'沉默',
                tip:'',
                ico:[6,2],
                pos:[2,3],
                key:['ANsi'],
                val:keys['ANsi'],
            },
            {
                tag:'生命吸取',
                tip:'',
                ico:[7,2],
                pos:[3,3],
                key:['ANdr'],
                val:keys['ANdr'],
            },
            {
                tag:'魅惑',
                tip:'',
                ico:[8,2],
                pos:[4,3],
                key:['ANch'],
                val:keys['ANch'],
            },
            选择技能
        ]
    },
    熊猫酒仙:{
        ico:[3,1],
        btn:[
            {
                tag:'火焰喷吐',
                tip:'',
                ico:[5,3],
                pos:[1,3],
                key:['ANbf'],
                val:keys['ANbf'],
            },
            {
                tag:'酒醉迷雾',
                tip:'',
                ico:[6,3],
                pos:[2,3],
                key:['ANdh'],
                val:keys['ANdh'],
            },
            {
                tag:'醉拳',
                tip:'',
                ico:[7,3],
                pos:[3,3],
                key:['ANdb'],
                val:keys['ANdb'],
            },
            {
                tag:'风暴、大地和火焰',
                tip:'',
                ico:[8,3],
                pos:[4,3],
                key:['ANef'],
                val:keys['ANef'],
            },
            选择技能
        ]
    },
    火焰领主:{
        ico:[4,1],
        btn:[
            {
                tag:'点燃',
                tip:'',
                ico:[5,4],
                pos:[1,3],
                key:['ANic','ANia'],
                val:keys['ANic'],
            },
            {
                tag:'召唤熔岩之爪',
                tip:'',
                ico:[6,4],
                pos:[2,3],
                key:['ANlm'],
                val:keys['ANlm'],
            },
            {
                tag:'灵魂燃烧',
                tip:'',
                ico:[7,4],
                pos:[3,3],
                key:['ANso'],
                val:keys['ANso'],
            },
            {
                tag:'熔岩爆发',
                tip:'',
                ico:[8,4],
                pos:[4,3],
                key:['ANvc'],
                val:keys['ANvc'],
            },
            选择技能
        ]
    },
    深渊魔王:{
        ico:[1,2],
        btn:[
            {
                tag:'火焰之雨',
                tip:'',
                ico:[5,5],
                pos:[1,3],
                key:['ANrf'],
                val:keys['ANrf'],
            },
            {
                tag:'恐惧之嚎',
                tip:'',
                ico:[6,5],
                pos:[2,3],
                key:['ANht'],
                val:keys['ANht'],
            },
            {
                tag:'顺势斩',
                tip:'',
                ico:[7,5],
                pos:[3,3],
                key:['ANca'],
                val:keys['ANca'],
            },
            {
                tag:'毁灭',
                tip:'',
                ico:[8,5],
                pos:[4,3],
                key:['ANdo'],
                val:keys['ANdo'],
            },
            选择技能
        ]
    },
    兽王:{
        ico:[2,2],
        btn:[
            {
                tag:'召唤灵熊',
                tip:'',
                ico:[5,6],
                pos:[1,3],
                key:['ANsg'],
                val:keys['ANsg'],
            },
            {
                tag:'召唤嚎猪',
                tip:'',
                ico:[6,6],
                pos:[2,3],
                key:['ANsq'],
                val:keys['ANsq'],
            },
            {
                tag:'召唤战鹰',
                tip:'',
                ico:[7,6],
                pos:[3,3],
                key:['ANsw'],
                val:keys['ANsw'],
            },
            {
                tag:'兽惊',
                tip:'',
                ico:[8,6],
                pos:[4,3],
                key:['ANst'],
                val:keys['ANst'],
            },
            选择技能
        ]
    },
    地精修补匠:{
        ico:[3,2],
        btn:[
            {
                tag:'口袋工厂',
                tip:'',
                ico:[5,7],
                pos:[1,3],
                key:['ANsy','ANs1','ANs2','ANs3'],
                val:keys['ANsy'],
            },
            {
                tag:'导弹轰炸',
                tip:'',
                ico:[6,7],
                pos:[2,3],
                key:['ANcs','ANc1','ANc2','ANc3'],
                val:keys['ANcs'],
            },
            {
                tag:'工程强化',
                tip:'',
                ico:[7,7],
                pos:[3,3],
                key:['ANeg'],
                val:keys['ANeg'],
            },
            {
                tag:'机械巨兽',
                tip:'',
                ico:[8,7],
                pos:[4,3],
                key:['ANrg','ANg1','ANg2','ANg3'],
                val:keys['ANrg'],
            },
            选择技能
        ]
    },
    炼金术士:{
        ico:[4,2],
        btn:[
            {
                tag:'治疗喷雾',
                tip:'',
                ico:[9,1],
                pos:[1,3],
                key:['ANhs'],
                val:keys['ANhs'],
            },
            {
                tag:'酸性炸弹',
                tip:'',
                ico:[10,1],
                pos:[2,3],
                key:['ANab'],
                val:keys['ANab'],
            },
            {
                tag:'化学狂暴',
                tip:'',
                ico:[11,1],
                pos:[3,3],
                key:['ANcr'],
                val:keys['ANcr'],
            },
            {
                tag:'点石成金',
                tip:'',
                ico:[12,1],
                pos:[4,3],
                key:['ANtm'],
                val:keys['ANtm'],
            },
            选择技能
        ]
    },
    末日守卫:{
        ico:[1,3],
        btn:[
            {
                tag:'驱散',
                tip:'',
                ico:[11,3],
                pos:[1,3],
                key:['Adsm'],
                val:keys['Adsm'],
            },
            {
                tag:'战争践踏',
                tip:'',
                ico:[11,2],
                pos:[2,3],
                key:['Awrs'],
                val:keys['Awrs'],
            },
            {
                tag:'残废',
                tip:'',
                ico:[12,2],
                pos:[3,3],
                key:['ACcr'],
                val:keys['ACcr'],
            },
            {
                tag:'火焰之雨',
                tip:'',
                ico:[5,5],
                pos:[4,3],
                key:['ACrf'],
                val:keys['ACrf'],
            },
        ]
    },
    风之熊猫:{
        ico:[2,3],
        btn:[
            {
                tag:'疾风步',
                tip:'',
                ico:[9,3],
                pos:[1,3],
                key:['ANwk'],
                val:keys['ANwk'],
            },
            {
                tag:'驱散',
                tip:'',
                ico:[11,3],
                pos:[2,3],
                key:['Adsm'],
                val:keys['Adsm'],
            },
            {
                tag:'飓风',
                tip:'',
                ico:[10,3],
                pos:[3,3],
                key:['ACcy'],
                val:keys['ACcy'],
            },
        ]
    },
    火之熊猫:{
        ico:[3,3],
        btn:[]
    },
    大地熊猫:{
        ico:[4,3],
        btn:[
            {
                tag:'嘲讽',
                tip:'',
                ico:[12,3],
                pos:[1,3],
                key:['ANta'],
                val:keys['ANta'],
            }
        ]
    },
    舰船:{
        ico:[1,4],
        btn:[
            {
                tag:'卸载',
                tip:'',
                ico:[10,4],
                pos:[2,3],
                key:['Sdro'],
                val:keys['Sdro'],
            },

        ]
    },
    飞艇:{
        ico:[2,4],
        btn:[
            {
                tag:'装载',
                tip:'',
                ico:[9,4],
                pos:[1,3],
                key:['Aloa'],
                val:keys['Aloa'],
            },
            {
                tag:'卸载',
                tip:'',
                ico:[10,4],
                pos:[2,3],
                key:['Adro'],
                val:keys['Adro'],
            }
        ]
    },
    灵熊:{
        ico:[3,4],
        btn:[
            {
                tag:'闪击',
                tip:'',
                ico:[9,2],
                pos:[1,3],
                key:['ANbl'],
                val:keys['ANbl'],
            }
        ]
    },
    地精机器人:{
        ico:[4,4],
        btn:[
            {
                tag:'Kaboom！',
                tip:'该键仅对修补匠的发条地精有效',
                ico:[10,2],
                pos:[1,3],
                key:['Asdg','Asd2','Asd3'],
                val:keys['Asdg'],
            }
        ]
    },
}

let orders = [移动,停止,保持,攻击,巡逻]
for(let item in unit){
    if(!unit[item].btn) unit[item].btn = []
    unit[item].btn.push(...orders)
}

module.exports = unit