const storage = require('main/const/storage')
let keys = require(storage + '/keys')

let { 集结点,互动 } = require("../general_arch")

let arch = {
    城镇中心:{
        ico:[1,5],
        btn:[
            {
                tag:'城镇中心升级',
                tip:'市政厅升级为要塞，要塞升级为城堡',
                ico:[10,7],
                pos:[1,3],
                key:['hkee','hcas'],
                val:keys['hkee'],
            },
            {
                tag:'人类农民',
                tip:"妙蛙种子，很喜欢叫你'老爷'",
                ico:[1,2],
                pos:[1,1],
                key:['hpea'],
                val:keys['hpea'],
            },
            {
                tag:'敲响警钟',
                tip:'将附近农民召集过来，再把他们变为民兵，武器盔甲不要钱，都白给',
                ico:[6,1],
                pos:[2,3],
                key:['Amic'],
                val:keys['Amic'],
            },
            {
                tag:'人类背包',
                tip:'让普通单位也能有两个包包，学裁缝是要花钱的',
                ico:[12,6],
                pos:[4,1],
                key:['Rhpm'],
                val:keys['Rhpm'],
            },
            集结点
        ]
    },
    兵营:{
        ico:[2,5],
        btn:[
            {
                tag:'步兵',
                tip:'一群妄图征服艾泽拉斯的不列颠人',
                ico:[2,2],
                pos:[1,1],
                key:['hfoo'],
                val:keys['hfoo'],
            },
            {
                tag:'火枪手',
                tip:'先喝酒后开枪，瞄准很慢，总打不准',
                ico:[3,2],
                pos:[2,1],
                key:['hrif'],
                val:keys['hrif'],
            },
            {
                tag:'骑士',
                tip:'马戏团出身，所以不戴头盔',
                ico:[4,2],
                pos:[3,1],
                key:['hkni'],
                val:keys['hkni'],
            },
            {
                tag:'防御技能',
                ico:[7,1],
                pos:[1,3],
                key:['Rhde'],
                val:keys['Rhde'],
            },
            {
                tag:'长管火枪',
                ico:[5,4],
                pos:[2,3],
                key:['Rhri'],
                val:keys['Rhri'],
            },
            {
                tag:'动物作战训练',
                ico:[6,4],
                pos:[3,3],
                key:['Rhan'],
                val:keys['Rhan'],
            },
            {
                tag:'裂甲之刃',
                tip:'',
                ico:[7,4],
                pos:[3,2],
                key:['Rhsb'],
                val:keys['Rhsb'],
            },
            集结点
        ]
    },
    伐木场:{
        ico:[3,5],
        btn:[
            {
                tag:'伐木工升级',
                ico:[7,5],
                pos:[1,1],
                key:['Rhlh'],
                val:keys['Rhlh'],
                map:2
            },
            {
                tag:'建筑强度升级',
                ico:[8,5],
                pos:[2,1],
                key:['Rhac'],
                val:keys['Rhac'],
                map:3
            }
        ]
    },
    铁匠铺:{
        ico:[4,5],
        btn:[
            {
                tag:'钢制武器升级',
                ico:[5,5],
                pos:[1,1],
                key:['Rhme'],
                val:keys['Rhme'],
                map:3
            },
            {
                tag:'火药升级',
                ico:[6,5],
                pos:[2,1],
                key:['Rhra'],
                val:keys['Rhra'],
                map:3
            },
            {
                tag:'钢制护甲升级',
                ico:[5,6],
                pos:[1,2],
                key:['Rhar'],
                val:keys['Rhar'],
                map:3
            },
            {
                tag:'皮制护甲升级',
                ico:[6,6],
                pos:[2,2],
                key:['Rhla'],
                val:keys['Rhla'],
                map:3
            },
        ]
    },
    农场:{
        ico:[1,6],
    },
    国王祭坛:{
        ico:[2,6],
        btn:[
            {
                tag:'召唤大法师',
                ico:[1,1],
                pos:[1,3],
                key:['Hamg'],
                val:keys['Hamg']
            },
            {
                tag:'召唤山丘之王',
                ico:[2,1],
                pos:[2,3],
                key:['Hmkg'],
                val:keys['Hmkg']
            },
            {
                tag:'召唤圣骑士',
                ico:[3,1],
                pos:[3,3],
                key:['Hpal'],
                val:keys['Hpal']
            },
            {
                tag:'召唤血法师',
                ico:[4,1],
                pos:[1,2],
                key:['Hblm'],
                val:keys['Hblm']
            },
            集结点
        ]
    },
    神秘圣地:{
        ico:[3,6],
        btn:[
            {
                tag:'训练女巫',
                ico:[1,3],
                pos:[1,1],
                key:['hsor'],
                val:keys['hsor'],
            },
            {
                tag:'训练牧师',
                ico:[2,3],
                pos:[2,1],
                key:['hmpr'],
                val:keys['hmpr'],
            },
            {
                tag:'训练破法者',
                ico:[3,3],
                pos:[3,1],
                key:['hspt'],
                val:keys['hspt'],
            },
            {
                tag:'女巫升级',
                ico:[5,7],
                pos:[1,3],
                key:['Rhst'],
                val:keys['Rhst'],
                map:2
            },
            {
                tag:'牧师升级',
                ico:[6,7],
                pos:[2,3],
                key:['Rhpt'],
                val:keys['Rhpt'],
                map:2
            },
            {
                tag:'研究魔法控制',
                ico:[8,7],
                pos:[3,2],
                key:['Rhss'],
                val:keys['Rhss'],
            },
            {
                tag:'研究隐形侦测',
                ico:[7,7],
                pos:[3,3],
                key:['AHta'],
                val:keys['AHta'],
            },
            集结点
        ]
    },
    车间:{
        ico:[4,6],
        btn:[
            {
                tag:'矮人直升机',
                ico:[1,4],
                pos:[1,1],
                key:['hgyr'],
                val:keys['hgyr'],
            },
            {
                tag:'迫击炮小队',
                ico:[2,4],
                pos:[2,1],
                key:['hmtm'],
                val:keys['hmtm'],
            },
            {
                tag:'蒸汽机车',
                ico:[3,4],
                pos:[3,1],
                key:[['hmtt'],['hrtt']],
                val:keys['hmtt'],
            },
            {
                tag:'研究直升机炸弹',
                ico:[9,5],
                pos:[1,2],
                key:['Rhgb'],
                val:keys['Rhgb'],
            },
            {
                tag:'研究速射机炮',
                ico:[12,5],
                pos:[1,3],
                key:['Rhfc'],
                val:keys['Rhfc'],
            },
            {
                tag:'研究爆炸碎片',
                ico:[10,5],
                pos:[2,2],
                key:['Rhfs'],
                val:keys['Rhfs'],
            },
            {
                tag:'研究轰天弹幕',
                ico:[11,5],
                pos:[3,2],
                key:['Rhrt'],
                val:keys['Rhrt'],
            },
            {
                tag:'研究照明弹',
                ico:[8,4],
                pos:[2,3],
                key:['Rhfl'],
                val:keys['Rhfl'],
            },
            集结点
        ]
    },
    哨塔:{
        ico:[1,7],
        btn:[
            {
                tag:'升级为箭塔',
                ico:[9,6],
                pos:[1,3],
                key:['hgtw'],
                val:keys['hgtw'],
            },
            {
                tag:'升级为炮塔',
                ico:[10,6],
                pos:[2,3],
                key:['hctw'],
                val:keys['hctw'],
            },
            {
                tag:'升级神秘之塔',
                ico:[11,6],
                pos:[3,3],
                key:['hatw'],
                val:keys['hatw'],
            }
        ]
    },
    狮鹫笼:{
        ico:[2,7],
        btn:[
            {
                tag:'训练龙鹰骑士',
                ico:[4,3],
                pos:[1,1],
                key:['hdhw'],
                val:keys['hdhw'],
            },
            {
                tag:'训练狮鹫骑士',
                ico:[4,4],
                pos:[2,1],
                key:['hgry'],
                val:keys['hgry'],
            },
            {
                tag:'研究蔽目乌云',
                ico:[8,3],
                pos:[1,3],
                key:['Rhcd'],
                val:keys['Rhcd'],
            },
            {
                tag:'研究风暴战锤',
                ico:[7,6],
                pos:[2,3],
                key:['Rhhb'],
                val:keys['Rhhb'],
            },
            集结点
        ]
    },
    人族商店:{
        ico:[3,7],
        btn:[
            互动
        ]
    },
    人类建造:{
        ico:[4,7],
        btn:[
            {
                tag:'城镇大厅',
                ico:[1,5],
                pos:[1,1],
                key:['htow'],
                val:keys['htow'],
            },
            {
                tag:'兵营',
                ico:[2,5],
                pos:[2,1],
                key:['hbar'],
                val:keys['hbar'],
            },
            {
                tag:'伐木场',
                ico:[3,5],
                pos:[3,1],
                key:['hlum'],
                val:keys['hlum'],
            },
            {
                tag:'铁匠铺',
                ico:[4,5],
                pos:[4,1],
                key:['hbla'],
                val:keys['hbla'],
            },
            {
                tag:'农场',
                ico:[1,6],
                pos:[1,2],
                key:['hhou'],
                val:keys['hhou'],
            },
            {
                tag:'国王祭坛',
                ico:[2,6],
                pos:[2,2],
                key:['halt'],
                val:keys['halt'],
            },
            {
                tag:'神秘圣地',
                ico:[3,6],
                pos:[3,2],
                key:['hars'],
                val:keys['hars'],
            },
            {
                tag:'车间',
                ico:[4,6],
                pos:[4,2],
                key:['harm'],
                val:keys['harm'],
            },
            {
                tag:'哨塔',
                ico:[1,7],
                pos:[1,3],
                key:['hwtw'],
                val:keys['hwtw'],
            },
            {
                tag:'狮鹫笼',
                ico:[2,7],
                pos:[2,3],
                key:['hgra'],
                val:keys['hgra'],
            },
            {
                tag:'人族商店',
                ico:[3,7],
                pos:[3,3],
                key:['hvlt'],
                val:keys['hvlt'],
            },

        ]
    }
}

module.exports = arch
