const storage = require('main/const/storage')
let keys = require(storage + '/keys')

let { 移动,停止,保持,攻击,巡逻,攻击地面,选择技能,影遁 } = require("../general_unit")

let unit = {
    '恶魔猎手':{
        ico:[1,1],
        btn:[
            {
                tag:'法力燃烧',
                tip:'这是一个很变态的技能',
                ico:[9,1],
                pos:[1,3],
                key:['AEmb'],
                val:keys['AEmb'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'献祭',
                tip:'',
                ico:[10,1],
                pos:[2,3],
                key:['AEim'],
                val:keys['AEim'],
                map:['Hotkey','Unhotkey','Researchhotkey']
            },
            {
                tag:'闪避',
                tip:'',
                ico:[11,1],
                pos:[3,3],
                key:['AEev'],
                val:keys['AEev'],
                map:['Researchhotkey']
            },
            {
                tag:'恶魔变身',
                tip:'',
                ico:[12,1],
                pos:[4,3],
                key:['AEme'],
                val:keys['AEme'],
                map:['Hotkey','Researchhotkey']
            },
            选择技能
        ]
    },
    丛林守护者:{
        ico:[2,1],
        btn:[
            {
                tag:'根须缠绕',
                tip:'',
                ico:[9,2],
                pos:[1,3],
                key:['AEer'],
                val:keys['AEer'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'自然之力',
                tip:'',
                ico:[10,2],
                pos:[2,3],
                key:['AEfn'],
                val:keys['AEfn'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'荆棘光环',
                tip:'',
                ico:[11,2],
                pos:[3,3],
                key:['AEah'],
                val:keys['AEah'],
                map:['Researchhotkey']
            },
            {
                tag:'宁静之雨',
                tip:'',
                ico:[12,2],
                pos:[4,3],
                key:['AEtq'],
                val:keys['AEtq'],
                map:['Hotkey','Researchhotkey']
            },
            选择技能
        ]
    },
    月女祭祀:{
        ico:[3,1],
        btn:[
            {
                tag:'侦查',
                tip:'',
                ico:[9,3],
                pos:[1,3],
                key:['AEst'],
                val:keys['AEst'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'灼热之箭',
                tip:'',
                ico:[10,3],
                pos:[2,3],
                key:['AHfa'],
                val:keys['AHfa'],
                map:['Hotkey','Unhotkey','Researchhotkey']
            },
            {
                tag:'强击光环',
                tip:'',
                ico:[11,3],
                pos:[3,3],
                key:['AEar'],
                val:keys['AEar'],
                map:['Researchhotkey']
            },
            {
                tag:'流星坠落',
                tip:'',
                ico:[12,3],
                pos:[4,3],
                key:['AEsf'],
                val:keys['AEsf'],
                map:['Hotkey','Researchhotkey']
            },
            选择技能,影遁
        ]
    },
    守望者:{
        ico:[4,1],
        btn:[
            {
                tag:'刀扇',
                tip:'',
                ico:[9,4],
                pos:[1,3],
                key:['AEfk'],
                val:keys['AEfk'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'闪烁',
                tip:'',
                ico:[10,4],
                pos:[2,3],
                key:['AEbl'],
                val:keys['AEbl'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'影击',
                tip:'',
                ico:[11,4],
                pos:[3,3],
                key:['AEsh'],
                val:keys['AEsh'],
                map:['Hotkey','Researchhotkey']
            },
            {
                tag:'复仇天神',
                tip:'',
                ico:[12,4],
                pos:[4,3],
                key:['AEsv'],
                val:keys['AEsv'],
                map:['Hotkey','Researchhotkey']
            },
            选择技能,影遁
        ]
    },
    小精灵:{
        ico:[1,2],
        btn:[
            {
                tag:'精灵建造',
                tip:'',
                ico:[4,7],
                pos:[1,3],
                key:['CmdBuildNightElf'],
                val:keys['CmdBuildNightElf'],
                map:['Hotkey']
            },
            {
                tag:'复苏',
                tip:'',
                ico:[8,8],
                pos:[2,2],
                key:['Aren'],
                val:keys['Aren'],
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'精灵采集',
                tip:'',
                ico:[9,8],
                pos:[4,2],
                key:['Awha'],
                val:keys['Awha'],
                map:['Hotkey']
            },
            {
                tag:'精灵自爆',
                tip:'',
                ico:[5,2],
                pos:[2,3],
                key:['Adtn'],
                val:keys['Adtn'],
                map:['Hotkey']
            },
        ]
    },
    弓箭手:{
        ico:[2,2],
        btn:[
            {
                tag:'骑乘角鹰兽',
                tip:'',
                ico:[4,3],
                pos:[1,3],
                key:['Aco2'],
                val:keys['Aco2'],
                map:['Hotkey']
            },
            影遁
        ]
    },
    女猎手:{
        ico:[3,2],
        btn:[
            {
                tag:'猫头鹰哨兵',
                tip:'',
                ico:[6,4],
                pos:[1,3],
                key:['Aesn'],
                val:keys['Aesn'],
                map:['Hotkey']
            },
            影遁
        ]

    },
    投刃车:{
        ico:[4,2],
        btn:[
            攻击地面
        ]
    },
    树妖:{
        ico:[1,3],
        btn:[
            {
                tag:'驱散',
                tip:'',
                ico:[5,3],
                pos:[1,3],
                key:['Aadm'],
                val:keys['Aadm'],
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    利爪德鲁伊:{
        ico:[2,3],
        btn:[
            {
                tag:'咆哮',
                tip:'',
                ico:[9,5],
                pos:[1,3],
                key:['Aroa','Ara2'],
                val:keys['Aroa'],
                map:['Hotkey']
            },
            {
                tag:'返老还童',
                tip:'',
                ico:[10,5],
                pos:[2,3],
                key:['Arej'],
                val:keys['Arej'],
                map:['Hotkey']
            },
            {
                tag:'熊形态',
                tip:'',
                ico:[11,5],
                pos:[4,3],
                key:['Abrf'],
                val:keys['Abrf'],
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    山岭巨人:{
        ico:[3,3],
        btn:[
            {
                tag:'嘲讽',
                tip:'',
                ico:[7,6],
                pos:[1,3],
                key:['Atau'],
                val:keys['Atau'],
                map:['Hotkey']
            },
            {
                tag:'战棍',
                tip:'',
                ico:[8,6],
                pos:[2,3],
                key:['Agra'],
                val:keys['Agra'],
                map:['Hotkey']
            },
        ]
    },
    角鹰兽骑士:{
        ico:[4,3],
        btn:[
            {
                tag:'卸下弓箭手',
                tip:'',
                ico:[2,2],
                pos:[1,3],
                key:['Adec'],
                val:keys['Adec'],
                map:['Hotkey']
            }
        ]
    },
    角鹰兽:{
        ico:[1,4],
        btn:[
            {
                tag:'搭载弓箭手',
                tip:'',
                ico:[4,3],
                pos:[1,3],
                key:['Aco3'],
                val:keys['Aco3'],
                map:['Hotkey']
            }
        ]
    },
    猛禽德鲁伊:{
        ico:[2,4],
        btn:[
            {
                tag:'精灵之火',
                tip:'',
                ico:[9,7],
                pos:[1,3],
                key:['Afae'],
                val:keys['Afae'],
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'飓风',
                tip:'',
                ico:[10,7],
                pos:[2,3],
                key:['Acyc'],
                val:keys['Acyc'],
                map:['Hotkey']
            },
            {
                tag:'变换形态',
                tip:'',
                ico:[11,7],
                pos:[4,3],
                key:['Arav'],
                val:keys['Arav'],
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    精灵龙:{
        ico:[3,4],
        btn:[
            {
                tag:'相位变换',
                tip:'',
                ico:[7,7],
                pos:[1,3],
                key:['Apsh'],
                val:keys['Apsh'],
                map:['Hotkey','Unhotkey']
            },
            {
                tag:'法力闪耀',
                tip:'',
                ico:[8,7],
                pos:[2,3],
                key:['Amfl'],
                val:keys['Amfl'],
                map:['Hotkey','Unhotkey']
            },
        ]
    },
    复仇者:{
        ico:[4,4],
        btn:[
            {
                tag:'复仇之魂',
                tip:'',
                ico:[9,6],
                pos:[1,3],
                key:['Avng'],
                val:keys['Avng'],
                map:['Hotkey']
            }
        ]
    }
}

let orders = [移动,停止,保持,攻击,巡逻]
for(let item in unit){
    if(!unit[item].btn) unit[item].btn = []
    unit[item].btn.push(...orders)
}

let arr = unit['小精灵'].btn
for(let i=0;i<arr.length;i++){
    if(arr[i].tag === '攻击'){
        unit['小精灵'].btn.splice(i, 1)
        break
    }
}

module.exports = unit