export { unit_human }

let unit_human = {
    大法师:{
        key:'[Hamg]',
        val:'A',
        ico:'1,1',
        btn:['暴风雪','水元素','辉煌光环','群体传送','选择技能']
    },
    山丘之王:{
        key:'[Hmkg]',
        val:'M',
        ico:'1,2',
        btn:['风暴之锤','雷霆一击','重击','天神下凡','选择技能']
    },
    圣骑士:{
        key:'[Hpal]',
        val:'L',
        ico:'1,3',
        btn:['圣光','无敌','专注光环','复活','选择技能']
    },
    血魔法师:{
        key:'[Hblm]',
        val:'B',
        ico:'1,4',
        btn:['烈焰风暴','放逐','魔法虹吸','召唤凤凰','选择技能']
    },
    农民:{
        key:'[hpea]',
        val:'Q',
        ico:'2,1',
        btn:['修理','采集','民兵','人类建造']
    },
    步兵:{
        key:'[hfoo]',
        val:'F',
        ico:'2,2',
        btn:['防御','取消防御']
    },
    火枪手:{
        key:'[hrif]',
        val:'R',
        ico:'2,3',
    },
    骑士:{
        key:'[hkni]',
        val:'A',
        ico:'2,4',
    },
    女巫:{
        key:'[hsor]',
        val:'S',
        ico:'3,1',
        btn:['减速','隐形术','变形术']
    },
    牧师:{
        key:'[hmpr]',
        val:'R',
        ico:'3,2',
        btn:['治疗','驱散','心灵之火']
    },
    破法者:{
        key:'[hspt]',
        val:'B',
        ico:'3,3',
        btn:['魔法盗取','魔法控制']
    },
    龙鹰:{
        key:'[hdhw]',
        val:'D',
        ico:'3,4',
        btn:['空中枷锁','蔽目乌云']
    },
    直升机:{
        key:'[hgyr]',
        val:'F',
        ico:'4,1',
    },
    迫击炮:{
        key:'[hmtm]',
        val:'A',
        ico:'4,2',
        btn:['照明弹','攻击地面']
    },
    蒸汽机车:{
        key:['[hmtt]','hrtt'],
        val:'E',
        ico:'4,3',
        btn:['照明弹','攻击地面']
    },
    狮鹫骑士:{
        key:'[hgry]',
        val:'G',
        ico:'4,4',
    },
}